name: C/C++ Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check code format and Auto format
        run: |
          find src example \( -name '*.c' -o -name '*.h' \) ! -name 'cJSON.c' ! -name 'cJSON.h' | xargs -r clang-format -style=file -i
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add src example
          git diff --cached --quiet || git commit -m "style: auto format code by clang-format"
          git push || echo "No changes to push"
