name: C/C++ Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check code format
        run: |
          find src example \( -name '*.c' -o -name '*.h' \) ! -name 'cJSON.c' ! -name 'cJSON.h' | xargs -r clang-format -style=file --dry-run --Werror
