name: C/C++ Coverage

on:
  push:
    branches: [ main, v* ]
  pull_request:
    branches: [ main, v* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov gcc cmake make

      - name: Configure CMake (with coverage flags)
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build && ctest --output-on-failure

      - name: Generate coverage report
        run: |
          lcov --capture --directory build --output-file coverage.info
          lcov --remove coverage.info '*/Unity/*' '*/cJSON/*' --output-file coverage.info
          lcov --list coverage.info
          genhtml coverage.info --output-directory out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: out
